# Generated by Django 4.0.6 on 2022-07-19 08:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_noticia', models.CharField(max_length=100)),
                ('materias', models.TextField()),
                ('foto_noticia', models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/')),
                ('data_noticia', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('publicada', models.BooleanField(default=False)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
